sudo: false
language: ruby
rvm:
  - 2.4.0
cache: bundler
git:
  submodules: false
before_install:
  - gem update --system
  - gem update bundler
script:
  - bundle exec rake spec
after_success:
  - echo "success"
after_failure:
  - echo "failure"
